apiVersion: apps/v1
kind: Deployment
metadata:
  name: accountrestservice
  labels:
    env: test
spec:
  replicas: 1 
  nodeSelector:
    roles: worker
  spec:
    containers:
    - name: accountrestservice
      image: ptrck0321/accountrestservice
      imagePullPolicy: IfNotPresent
      ports:
          - containerPort: 9000
